export const EVENTS_REQUEST = 'EVENTS_REQUEST';
export const EVENTS_FAILURE = 'EVENTS_FAILURE';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_EXISTING = 'EVENTS_EXISTING';
export const EVENTS_ERROR = 'EVENTS_ERROR';
