export const NEWSLETTERS_REQUEST = 'NEWSLETTERS_REQUEST';
export const NEWSLETTERS_FAILURE = 'NEWSLETTERS_FAILURE';
export const NEWSLETTERS_SUCCESS = 'NEWSLETTERS_SUCCESS';
export const NEWSLETTERS_EXISTING = 'NEWSLETTERS_EXISTING';
export const NEWSLETTERS_ERROR = 'NEWSLETTERS_ERROR';
