export const NEWSLETTER_REQUEST = 'NEWSLETTER_REQUEST';
export const NEWSLETTER_FAILURE = 'NEWSLETTER_FAILURE';
export const NEWSLETTER_SUCCESS = 'NEWSLETTER_SUCCESS';
export const NEWSLETTER_EXISTING = 'NEWSLETTER_EXISTING';
export const NEWSLETTER_ERROR = 'NEWSLETTER_ERROR';
